# ----------------------------------------------------------------------
# Site settings
# ----------------------------------------------------------------------
title: "Michael Ajao-Olarinoye" # Title for the site, shown in browser title bar
first_name: Michael
middle_name: 
last_name: Ajao-Olarinoye
email: ajaoolarinoyemichael@gmail.com # Your email address
description: > # Description for your site (for SEO)
  Personal portfolio showcasing data science projects, machine learning research, and educational contributions.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: "Data Science, Machine Learning, AI, Educator, Academic Portfolio, Research" # Keywords for SEO optimization
lang: en # Language of the site
icon: ⚛️ # Favicon for your site (can also be a path to an image)

# URL settings
url: "https://michaelajao.github.io" # The URL for the live site
baseurl: "" # Keep blank unless you have a subdirectory for your site
last_updated: true # Set to true to show the last updated date in the footer
impressum_path: # GDPR impressum link
back_to_top: true # Back to top button

# ----------------------------------------------------------------------
# Theme Settings
# ----------------------------------------------------------------------
# GitHub repository themes for personal projects display
repo_theme_light: default # GitHub light theme for repositories
repo_theme_dark: dark # GitHub dark theme for repositories
repo_trophies:
  enabled: true
  theme_light: flat # Trophy style for light theme
  theme_dark: gitdimmed # Trophy style for dark theme

# RSS Feed
rss_icon: true # RSS feed for your blog

# ----------------------------------------------------------------------
# Layout and Responsiveness
# ----------------------------------------------------------------------
navbar_fixed: true # Keep navbar fixed
footer_fixed: true # Keep footer fixed
search_enabled: true # Enable search
socials_in_search: true # Show social links in search
bib_search: true # Enable publication search
max_width: 100% # Ensure the site is responsive across devices
min_width: 320px # Minimum width for smaller devices (mobile)

# ----------------------------------------------------------------------
# Open Graph and Schema.org for Social Media Previews
# ----------------------------------------------------------------------
serve_og_meta: true # Open Graph meta tags for social sharing
serve_schema_org: true # Schema.org metadata for structured data
og_image: /assets/img/og-image.jpg # Open Graph image for previews

# ----------------------------------------------------------------------
# Social Integration
# ----------------------------------------------------------------------
# Social media profiles
github_username: michaelajao
linkedin_username: michael-ajao
twitter_username: michaelajao
scholar_userid: qc6CJjYAAAAJ # Google Scholar ID
research_gate_profile: # Add your ResearchGate link here
orcid_id: # Add your ORCID ID if applicable
youtube_id: # Add your YouTube channel ID if needed

contact_note: >
  Feel free to reach out to me via any of the platforms below!

# ----------------------------------------------------------------------
# Analytics and Search Engine Verification
# ----------------------------------------------------------------------
google_analytics: G-XXXXXXXXXX # Google Analytics tracking ID
google_site_verification: XXXXXXXXXXXXXXXXXX # Verification for Google Search Console
bing_site_verification: XXXXXXXXXXXXXXXXXX # Verification for Bing Webmaster Tools

# ----------------------------------------------------------------------
# Blog Settings
# ----------------------------------------------------------------------
blog_name: Michael's Blog # Blog name to be displayed
blog_description: Posts on data science, machine learning, and research.
permalink: /blog/:year/:title/ # URL format for blog posts

# Pagination settings
pagination:
  enabled: true
  per_page: 5 # Number of posts per page

# Enable related blog posts for better user engagement
related_blog_posts:
  enabled: true
  max_related: 5 # Show up to 5 related posts

# Giscus comments for blog posts (if using GitHub Discussions for comments)
giscus:
  repo: michaelajao/michaelajao.github.io
  repo_id: XXXXXXXXXX
  category: Comments
  category_id: XXXXXXXXXX
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en

# ----------------------------------------------------------------------
# Newsletter Subscription
# ----------------------------------------------------------------------
newsletter:
  enabled: false
  endpoint: # Your email subscription endpoint if applicable

# ----------------------------------------------------------------------
# Projects and Collections
# ----------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/

# Announcements section
announcements:
  enabled: true
  scrollable: true
  limit: 5 # Show up to 5 announcements

# Latest posts section
latest_posts:
  enabled: true
  scrollable: true
  limit: 3 # Show up to 3 recent posts

# ----------------------------------------------------------------------
# Jekyll Settings
# ----------------------------------------------------------------------
# Markdown processing and code highlighting settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: false
      start_line: 1
    span:
      line_numbers: false

# Exclude files and folders from the site build
# Includes & excludes
include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor

keep_files:
  - CNAME
  - .nojekyll

# Plugins for extended functionality
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed


# ----------------------------------------------------------------------
# Additional Optimization and Features
# ----------------------------------------------------------------------
jekyll-minifier:
  exclude: ["robots.txt", "assets/js/search/*.js"]
  uglifier_args:
    harmony: true

# Archives and tags
jekyll-archives:
  enabled: [year, tags, categories] # Enable archives by year, tags, and categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"

# Scholar plugin settings for managing academic publications
scholar:
  last_name: [Ajao-Olarinoye]
  first_name: [Michael]
  style: apa
  source: /_bibliography/
  bibliography: papers.bib
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

# Enable publication badges (Altmetric, Google Scholar, etc.)
enable_publication_badges:
  altmetric: true
  google_scholar: true

# ----------------------------------------------------------------------
# Responsive Images and Performance Optimization
# ----------------------------------------------------------------------
imagemagick:
  enabled: false # Enable responsive images
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  output_formats:
    webp: "-quality 85"

lazy_loading_images: true # Enable lazy loading for images

# Enable dark mode, medium zoom on images, etc.
enable_darkmode: true
enable_medium_zoom: true
enable_progressbar: true # Progress bar at the top during scrolling
enable_masonry: true # Auto-arrange project cards

# ----------------------------------------------------------------------
# Footer settings
# ----------------------------------------------------------------------
footer:
  content: |
    <p>&copy; 2024 Michael Ajao-Olarinoye. All Rights Reserved.</p>
    <p>Email: <a href="mailto:ajaoolarinoyemichael@gmail.com">ajaoolarinoyemichael@gmail.com</a> | GitHub: <a href='https://github.com/michaelajao'>michaelajao</a></p>
    <p>Coventry, UK</p>

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json # it can also be an url
jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
