# # -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Michael Ajao Portfolio # The website title
first_name: Michael
middle_name: O.
last_name: Ajao
email: ajaoolarinoyemichael@gmail.com
description: >
  Data Scientist and Machine Learning Expert with over 5 years of experience in data analysis, machine learning, and web/mobile development.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Images used are either personal or from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: data-science, machine-learning, portfolio, academic, web-development
lang: en
icon: ⚛️
url: https://michaelajao.github.io # GitHub Pages URL
baseurl: "" # The subpath of your site, leave blank for root deployment on GitHub Pages
last_updated: true # Display last updated in the footer
impressum_path: # Leave this blank unless you need an impressum link for GDPR compliance
back_to_top: true # Enable the back-to-top button


# SEO Settings
seo:
  title: "Michael Ajao-Olarinoye | Data Scientist & Machine Learning Engineer"
  description: "Personal portfolio website of Michael Ajao-Olarinoye, showcasing data science projects, machine learning research, and educational contributions."
  keywords: "Data Science, Machine Learning, Deep Learning, Educator, Research, AI"
  canonical: true
  twitter_card: summary_large_image
  twitter_site: "@michaelajao"
  og_image: "/assets/img/og-image.jpg" # Use a custom Open Graph image for better link sharing.


# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
# Theme and Plugins
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default # skin options: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
bib_search: true
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image: # Add if you have a site-wide Open Graph image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: michaelajao
linkedin_username: michael-ajao
orcid_id: 0000-0003-2763-8293
scholar_userid: qc6CJjYAAAAJ

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics: # Your Google Analytics measurement ID (format: G-XXXXXXXXXX)
cronitor_analytics: # Your Cronitor Analytics site ID
pirsch_analytics: # Your Pirsch Analytics site ID
google_site_verification: # Your Google Search Console verification ID
bing_site_verification: # Your Bing Search Console verification ID

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Michael Ajao's Blog
blog_description: A blog about data science, machine learning, and web development.
permalink: /blog/:year/:title/
lsi: false # Use Latent Semantic Indexing for related posts
pagination:
  enabled: true
related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Giscus comments (Optional)
# -----------------------------------------------------------------------------

giscus:
  repo: michaelajao/michaelajao.github.io
  repo_id: # Leave empty unless you have the repo ID
  category: Comments
  category_id: # Leave empty unless you have the category ID
  mapping: title
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  lang: en

# -----------------------------------------------------------------------------
# Disqus comments (DEPRECATED)
# -----------------------------------------------------------------------------

# disqus_shortname: al-folio # Set this if you plan to use Disqus comments

# -----------------------------------------------------------------------------
# External sources
# -----------------------------------------------------------------------------

# external_sources:
#   - name: medium.com
#     rss_url: https://medium.com/feed/@michaelajao
#   - name: Google Blog
#     posts:
#       - url: https://blog.google/technology/ai/google-gemini-update-flash-ai-assistant-io-2024/
#         published_date: 2024-05-14

# -----------------------------------------------------------------------------
# Newsletter (Optional)
# -----------------------------------------------------------------------------

newsletter:
  enabled: false
  endpoint: 

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/

announcements:
  enabled: true
  scrollable: true
  limit: 5

latest_posts:
  enabled: true
  scrollable: true
  limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# -----------------------------------------------------------------------------
# Plug-ins
# -----------------------------------------------------------------------------
# Includes & excludes
include: ["_pages"]
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
keep_files:
  - CNAME
  - .nojekyll


# header_pages:
#   - /about.md
#   - /projects.md
#   - /cv.md
#   - /publications.md
#   - /repositories.md
#   - /teaching.md


plugins:
  - minimal-mistakes-jekyll
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_darkmode: true # Enables switching between light/dark modes.
enable_progressbar: true # Enables a horizontal progress bar linked to the vertical scroll position.
enable_video_embedding: false # Disable video embedding for bibtex entries.
enable_masonry: true # Enables automatic project cards arrangement
enable_math: true # Enables math typesetting using MathJax
enable_tooltips: false # Disables automatic tooltip links for sections
enable_navbar_social: false # Disables social links in the navbar on the about page
enable_project_categories: true # Enables categorization of projects into multiple categories
enable_medium_zoom: true # Enables image zoom feature (like medium.com)

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

third_party_libraries:
  download: false
  bootstrap-table:
    version: "1.22.4"
  chartjs:
    version: "4.4.1"
  d3:
    version: "7.8.5"
  echarts:
    version: "5.5.0"
  jquery:
    version: "3.6.0"

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------
imagemagick:
  enabled: false # enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_formats:
    webp: "-quality 85"


# -----------------------------------------------------------------------------
# Lazy loading images
# -----------------------------------------------------------------------------

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [year, tags, categories]
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"

display_tags: ["formatting", "images", "links", "math", "code", "blockquotes"] # these tags will be displayed on the front page of your blog
display_categories: ["external-services"] # these categories will be displayed on the front page of your blog

# -----------------------------------------------------------------------------
# Scholar configuration (for academic citations and publications)
# -----------------------------------------------------------------------------

# scholar:
#   last_name: [Ajao]
#   first_name: [Michael]
#   style: apa
#   locale: en
#   source: /_bibliography/
#   bibliography: papers.bib
#   bibliography_template: bib
#   replace_strings: true
#   join_strings: true

#   max_author_limit: 3
#   enable_publication_thumbnails: true
#   enable_publication_badges:
#     altmetric: true
#     dimensions: true
#     google_scholar: true

#   bibtex_filters: [latex, smallcaps, superscript]


#   details_dir: bibliography
#   details_link: Details

#   query: "@*"
#   group_by: year
#   group_order: descending
# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ["robots.txt", "assets/js/search/*.js"]
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Sitemap settings
# -----------------------------------------------------------------------------

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed
# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json # JSON for resume


