# Site settings
title: Miolaj
first_name: Michael
last_name: Ajao-Olarinoye
email: ajaoolarinoyemichael@gmail.com
description: >
  Data Scientist, Machine Learning Engineer, and Educator with expertise in 
  deep learning, NLP, and predictive analytics. Building innovative solutions 
  in data-driven projects.

baseurl: "" # If hosting on a subpath (e.g., /blog)
url: "https://michaelajao.github.io" # Base hostname & protocol
twitter_username: michaelajao
github_username: michaelajao
linkedin_username: michael-ajao

# Site-specific settings
search: true
bib_search: true

# SEO and meta tags
lang: en
author: "Michael Ajao-Olarinoye"

# Theme and plugins
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-regex-replace
  - jekyll-jupyter-notebook

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Social links (for use across the site)
social_links:
  - name: "GitHub"
    url: "https://github.com/michaelajao"
    icon: "fab fa-github"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/michael-ajao"
    icon: "fab fa-linkedin"
  - name: "Twitter"
    url: "https://twitter.com/michaelajao"
    icon: "fab fa-twitter"

# Sitemap configuration
sitemap:
  changefreq: weekly
  priority: 0.7

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Google Analytics tracking (Optional)
google_analytics: "UA-XXXXX-Y"

# Disqus integration (Optional)
disqus:
  shortname: your-disqus-shortname
