# ------------------------------------------------------------------------------
# Site Settings
# ------------------------------------------------------------------------------
# These settings customize the basic aspects of your website such as the title, 
# description, and base URL. This information will be used throughout the site.
title: "Michael Ajao-Olarinoye" # Your site's title.
first_name: Michael # Your first name.
last_name: Ajao-Olarinoye # Your last name.
email: ajaoolarinoyemichael@gmail.com # Your email address.
description: > # A brief description of your website that will appear in search engines and previews.
  Personal portfolio showcasing data science projects, machine learning research, and educational contributions.
baseurl: "" # Leave this empty unless using a custom subpath.
url: "https://michaelajao.github.io" # The main URL for your site (use your custom domain if applicable).
twitter_username: michaelajao # Twitter handle.
github_username: michaelajao # GitHub handle.

# ------------------------------------------------------------------------------
# SEO Optimization
# ------------------------------------------------------------------------------
# These settings are critical for search engine optimization (SEO), ensuring 
# that your site is discoverable on search engines like Google.
seo:
  title: "Michael Ajao-Olarinoye | Data Scientist & Machine Learning Engineer"
  description: "Personal portfolio showcasing data science projects, machine learning research, and educational contributions."
  keywords: "Data Science, Machine Learning, Deep Learning, Educator, Research, AI"
  canonical: true # Adds a canonical URL for better SEO practices.
  twitter_card: summary_large_image # Sets the Twitter card format for preview.
  twitter_site: "@michaelajao" # Twitter handle for social sharing.
  og_image: "/assets/img/og-image.jpg" # Open Graph image (used when sharing links on social media).

# ------------------------------------------------------------------------------
# Language and Icons
# ------------------------------------------------------------------------------
# Language setting and custom icon settings, including favicons.
lang: en # The language code for your site (English).
icon: ⚛️ # The emoji used as the favicon (use a custom image if needed).

# ------------------------------------------------------------------------------
# Build Settings
# ------------------------------------------------------------------------------
# Defines the Jekyll theme and important plugins to be used.
theme: minimal-mistakes-jekyll # Jekyll theme used for your website.

# Plugins are necessary for various features such as social media integration,
# pagination, and performance optimization.
plugins:
  - jekyll-sitemap # Generates a sitemap for search engines.
  - jekyll-gist # Allows embedding GitHub Gists.
  - jekyll-feed # Generates an RSS feed for your blog.
  - jekyll-redirect-from # Adds redirection capabilities.
  - jekyll-archives # Organizes older blog posts into archives.
  - jekyll-email-protect # Protects email addresses from spambots.
  - jekyll-get-json # Fetches external JSON data.
  - jekyll-imagemagick # Optimizes images.
  - jekyll-jupyter-notebook # Allows embedding Jupyter Notebooks.
  - jekyll-link-attributes # Adds attributes to links (e.g., "nofollow").
  - jekyll-minifier # Minifies HTML/CSS/JS to improve performance.
  - jekyll-paginate-v2 # Handles pagination of blog posts.
  - jekyll-regex-replace # Enables regex-based text replacement.
  - jekyll/scholar # Manages scholarly publications.
  - jekyll-tabs # Enables tabbed content.
  - jekyll-toc # Automatically generates tables of contents.
  - jekyll-twitter-plugin # Adds Twitter embeds.
  - jemoji # Adds emoji support to markdown.

# ------------------------------------------------------------------------------
# Excluded Files and Folders
# ------------------------------------------------------------------------------
# Files and folders that should be excluded from the site build process.
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - package.json
  - package-lock.json
  - vendor/

# Files that should always be kept in the repository.
keep_files:
  - CNAME
  - .nojekyll
  - .env

# ------------------------------------------------------------------------------
# Theme Settings
# ------------------------------------------------------------------------------
# Custom theme settings for visual customization, including GitHub themes for 
# repositories.
repo_theme_light: default # GitHub light theme for repository cards.
repo_theme_dark: dark # GitHub dark theme for repository cards.
repo_trophies:
  enabled: true
  theme_light: flat # Light theme for GitHub trophies.
  theme_dark: gitdimmed # Dark theme for GitHub trophies.

rss_icon: true # Displays an RSS feed icon.

# ------------------------------------------------------------------------------
# Layout and Responsiveness
# ------------------------------------------------------------------------------
# Configures layout settings for the website, including a fixed navigation bar 
# and footer. Also adjusts responsiveness for different screen sizes.
navbar_fixed: true # Keeps the navigation bar fixed at the top.
footer_fixed: true # Keeps the footer fixed at the bottom.
search_enabled: true # Enables site search functionality.
socials_in_search: true # Includes social media links in search results.
bib_search: true # Allows searching through publications.
max_width: 100% # Ensures the layout is responsive across all devices.
min_width: 320px # Ensures proper display on small mobile devices.

# ------------------------------------------------------------------------------
# Markdown and Syntax Highlighting
# ------------------------------------------------------------------------------
# Configures markdown processing and syntax highlighting for code snippets.
markdown: kramdown
highlighter: rouge # Code syntax highlighter.
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: false # Disables line numbers for code blocks.
      start_line: 1
    span:
      line_numbers: false # Disables line numbers for inline code.

# ------------------------------------------------------------------------------
# Social Media and Contact Links
# ------------------------------------------------------------------------------
# Settings for social media profiles and icons that will be displayed on the site.
social:
  twitter: "michaelajao" # Twitter handle.
  github: "michaelajao" # GitHub profile.
  linkedin: "michael-ajao" # LinkedIn profile.
  scholar: "https://scholar.google.com/citations?user=XXXXX" # Google Scholar profile link.

social_icons:
  enabled: true
  twitter: true
  github: true
  linkedin: true
  scholar: true

# ------------------------------------------------------------------------------
# Pagination
# ------------------------------------------------------------------------------
# Settings to handle pagination for blog posts and projects.
paginate: 5 # Number of posts per page.
paginate_path: "/page:num/" # URL format for pagination.

# ------------------------------------------------------------------------------
# Google Analytics
# ------------------------------------------------------------------------------
# Adds Google Analytics for tracking website traffic.
google_analytics: "UA-XXXXXXXXX-X" # Your Google Analytics tracking ID.

# ------------------------------------------------------------------------------
# Footer Settings
# ------------------------------------------------------------------------------
# Configures the footer content with contact information and social links.
footer:
  content: |
    <p>&copy; 2024 Michael Ajao-Olarinoye. All Rights Reserved.</p>
    <p>Email: ajaoolarinoyemichael@gmail.com | GitHub: <a href='https://github.com/michaelajao'>michaelajao</a></p>
    <p>Coventry, UK</p>

# ------------------------------------------------------------------------------
# Performance Optimization
# ------------------------------------------------------------------------------
# Settings to improve site performance by optimizing and compressing assets.
assets:
  compress: true # Enable asset compression.
  js_compressor: terser # JavaScript compression.
  css_compressor: cssnano # CSS compression.
